This is a markdown cell.

In [18]:
import pandas as pd
import dateutil

df = pd.read_csv('../../data/Pedacyclist_Map_data.tsv', sep='\t', encoding='utf-16le')
# df['Crash Severity Custom Desc'].str.contains('Fatality')
# print df

# Reading this: https://www.shanelynn.ie/summarising-aggregation-and-grouping-data-in-python-pandas/

df.info()
df['Crash Severity Custom Desc'].count()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1097 entries, 0 to 1096
Data columns (total 13 columns):
Crash Severity Custom Desc    1097 non-null object
Alchl Invlv Flg               1097 non-null object
Crash Speed Invlv Flg         1097 non-null object
Crash Yr No                   1097 non-null int64
Drug Invlv Flg                1097 non-null object
Fc Desc                       1097 non-null object
Lat Dd                        1097 non-null float64
Longtd Dd                     1097 non-null float64
Roadway Character             1097 non-null object
Tot Inj Lvl A Cnt             1097 non-null int64
Tot Inj Lvl B Cnt             1097 non-null int64
Tot Inj Lvl C Cnt             1097 non-null int64
Tot Pedcycl Fatal Cnt         1097 non-null int64
dtypes: float64(2), int64(5), object(6)
memory usage: 111.5+ KB

1097

In [30]:
# df.groupby(['Crash Yr No']).groups.keys()
df.groupby(['Crash Yr No']).describe()

            Lat Dd                                                        \
             count       mean       std        min        25%        50%
Crash Yr No
2007          99.0  44.038110  0.061719  43.744600  44.040040  44.048833
2008         100.0  44.047529  0.044083  43.794061  44.043348  44.047856
2009          78.0  44.052086  0.045166  43.793993  44.042769  44.048779
2010         103.0  44.052841  0.045028  43.791957  44.045124  44.051589
2011         107.0  44.038858  0.067104  43.788730  44.040031  44.047719
2012         105.0  44.052901  0.051527  43.797214  44.045100  44.053216
2013         129.0  44.047661  0.048572  43.747226  44.040726  44.045814
2014         150.0  44.049878  0.048926  43.746483  44.044442  44.051350
2015         122.0  44.049209  0.051464  43.797236  44.043447  44.052817
2016         104.0  44.050629  0.036046  43.804822  44.045775  44.048071

                                  Longtd Dd             ...   \
                   75%        max     count        mean ...
Crash Yr No                                             ...
2007         44.063346  44.115688      99.0 -123.085223 ...
2008         44.063902  44.117087     100.0 -123.112850 ...
2009         44.063806  44.218231      78.0 -123.093376 ...
2010         44.062812  44.222565     103.0 -123.079407 ...
2011         44.063041  44.220018     107.0 -123.104649 ...
2012         44.063999  44.224274     105.0 -123.083595 ...
2013         44.056540  44.219002     129.0 -123.118531 ...
2014         44.063648  44.219193     150.0 -123.097400 ...
2015         44.069968  44.229794     122.0 -123.108645 ...
2016         44.064608  44.113067     104.0 -123.089933 ...

            Tot Inj Lvl C Cnt      Tot Pedcycl Fatal Cnt                      \
                          75%  max                 count      mean       std
Crash Yr No
2007                      1.0  2.0                  99.0  0.030303  0.172292
2008                      1.0  2.0                 100.0  0.010000  0.100000
2009                      1.0  2.0                  78.0  0.012821  0.113228
2010                      1.0  2.0                 103.0  0.009709  0.098533
2011                      1.0  3.0                 107.0  0.037383  0.190592
2012                      1.0  2.0                 105.0  0.019048  0.137348
2013                      1.0  2.0                 129.0  0.007752  0.088045
2014                      1.0  2.0                 150.0  0.013333  0.115082
2015                      1.0  2.0                 122.0  0.008197  0.090536
2016                      1.0  3.0                 104.0  0.000000  0.000000


             min  25%  50%  75%  max
Crash Yr No
2007         0.0  0.0  0.0  0.0  1.0
2008         0.0  0.0  0.0  0.0  1.0
2009         0.0  0.0  0.0  0.0  1.0
2010         0.0  0.0  0.0  0.0  1.0
2011         0.0  0.0  0.0  0.0  1.0
2012         0.0  0.0  0.0  0.0  1.0
2013         0.0  0.0  0.0  0.0  1.0
2014         0.0  0.0  0.0  0.0  1.0
2015         0.0  0.0  0.0  0.0  1.0
2016         0.0  0.0  0.0  0.0  0.0

[10 rows x 48 columns]

Number of events for each year:

In [29]:
df['Crash Yr No'].value_counts()

2014    150
2013    129
2015    122
2011    107
2012    105
2016    104
2010    103
2008    100
2007     99
2009     78
Name: Crash Yr No, dtype: int64